steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sustained-opus-269301/prasadtechnology/cicdgcprun:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/sustained-opus-269301/prasadtechnology/cicdgcprun:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run','deploy','cloudbuildyml-service', '--platform=managed','--region=us-central1', '--image=gcr.io/sustained-opus-269301/prasadtechnology/cicdgcprun:$SHORT_SHA']
